### ISSUE TITLE
Arxiv is super careful with emails so maybe we should be too

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/arxiv-vanity#124]
https://arxiv.org/help/email-protection

We do obfuscate with Cloudflare, but that doesn't protect against just rendering the page in a browser. We could just strip emails entirely.

**Comment by wonjininfo** [comment]
Hi @bfirsh , 
Thank you for making this tool and made its code publicly available!!

I am also worried about this matter. 
I was quite surprised that my email address is cached by google bot from your website. 

I would like to request a deletion of me and my colleague's email addresses in [this paper](https://www.arxiv-vanity.com/papers/1809.07950/). 
The email addresses are shown in `Research` section right after the abstract. 
Thanks!

**Comment by bfirsh** [comment]
@wonjininfo Ah – this is a tough one because it shows up in an error message! Hmm. Let me see if I can write a regexp to filter out email addresses. If not I might have to disable your paper completely, if you don't mind...

**Comment by bfirsh** [comment]
@wonjininfo Looks like the latest version of your paper doesn't have latex source, so I've re-rendered and I accidentally fixed the problem. 😂

In the meantime I will have a go at filtering out email addresses from all other papers. I think it is unexpected behaviour -- an email address in a PDF feels safer from spammers somehow.

**Comment by wonjininfo** [comment]
@bfirsh Thank you so much for your prompt and kind response!

**Comment by bfirsh** [comment]
Thank you for the reminder to fix this! Deploying now, and all caches should be cleared in an hour or so...
