### ISSUE TITLE
Paper not rendered despite source available

### ISSUE THREAD

**Issue by mu22le** [arxiv-vanity/arxiv-vanity#325]
https://arxiv.org/abs/1808.07808 has sources but 
https://www.arxiv-vanity.com/papers/1808.07808/ says "This paper doesn't have LaTeX source code, so it can't be rendered as a web page."

Possibly because the source is served as an uncompressed tex file with no extension?

**Comment by bfirsh** [comment]
Ooh - yes probably. I _think_ this fixed in a new version of Arxiv Vanity which just blindly tries to render everything instead of trying to figure out whether it can render it or not. I shall leave this open to remind to test though. Thank you!

**Comment by jure** [comment]
Same issue with https://arxiv.org/abs/1901.00020v1, if that helps with debugging. When it does work, it's beautiful :)
