### ISSUE TITLE
requested URL not found

### ISSUE THREAD

**Issue by cascella** [arxiv-vanity/arxiv-vanity#335]
If I try to "vanitize" this URL: https://arxiv.org/abs/hep-ph/0703260

By adding "-vanity" to the hostname I get the following error: 
"Not Found
The requested URL /papers/hep-ph/0703260 was not found on this server."

If I use the form on the homepage i get "Could not find Arxiv ID in that URL. "

But the article exists and, apparently, the sources are available.

**Comment by bfirsh** [comment]
This is #69. Thanks for the report!
