### ISSUE TITLE
Please provide an example of what an ArXiv URL looks like

### ISSUE THREAD

**Issue by AkshatM** [arxiv-vanity/arxiv-vanity#382]
I'm a first time user. After trying `https://arxiv.org/pdf/gr-qc/9806119.pdf` as an ArXiv URL, I received a `Could not find ArXiv ID in this URL` error on submission.

Removing the protocol, using the abstract page URL, eliminating the `.pdf` - nothing worked.

Undeterred, I poked around at the source, hoping there was an example of a valid URL I _could_ use. Instead, I met this function, which checks matches for three different regexes:

https://github.com/arxiv-vanity/arxiv-vanity/blob/603965a17c80fe5424af8a96639faf55ea3eebdc/arxiv_vanity/papers/views.py#L126

each of which is pretty damn ugly to understand

https://github.com/arxiv-vanity/arxiv-vanity/blob/603965a17c80fe5424af8a96639faf55ea3eebdc/arxiv_vanity/papers/views.py#L119
https://github.com/arxiv-vanity/arxiv-vanity/blob/603965a17c80fe5424af8a96639faf55ea3eebdc/arxiv_vanity/papers/views.py#L120
https://github.com/arxiv-vanity/arxiv-vanity/blob/603965a17c80fe5424af8a96639faf55ea3eebdc/arxiv_vanity/papers/views.py#L121

I cannot, for the life of me, figure out what kind of URL is being expected here simply by eyeballing the regexes themselves. 

I still cannot use arxiv-vanity because I have yet to find a URL that actually works (I've already spent ten minutes playing around with these expressions on [Pythex](https://pythex.org/)).

# Ask

1. Please provide an actual example of what valid ArXiv URLs look like on the home page. This will prevent frustrated users like me thinking it'll "just work" with reasonable input. I understand the desire to present a simple interface, but my experience was not a pleasant user experience.

2. Please either update your regular expressions to use *named* groups, at least (named groups are a lot easier to understand because they actually name the expected components inside the regex, meaning it's easy to understand what URL components are being looked at). 

    Or better still use [parser combinators e.g. `parsy`](https://parsy.readthedocs.io/en/latest/overview.html) to extract input - parser combinators both provide explanation for *why* a URL does not match on failure (something the regex library cannot do) *and* are semantically easier to read than raw regexes in the source code. 

    Doing this will make more useful error messages possible for the end user.

**Comment by bfirsh** [comment]
Thanks for the suggestion! The particular issue of that URL has actually just been fixed by #380.

I agree some examples of what an arXiv URL would be useful. I'm not sure there is enough space on the home page, but perhaps a list of the sort of URLs that work could be displayed on the error page? That way it'll help people who aren't doing it right, without adding cognitive load for people who know what they are doing.

If you'd be willing to submit a pull request, it would be very much appreciated. :)
