### ISSUE TITLE
arxiv-vanity.com gives 500 error messages for all new papers?

### ISSUE THREAD

**Issue by nottombrown** [arxiv-vanity/arxiv-vanity#415]
Love this service, but unfortunately it appears to have been down for the last couple days. For example, both of these papers fail with an opaque 500 message

https://www.arxiv-vanity.com/convert/?query=https://arxiv.org/abs/1906.06362

https://www.arxiv-vanity.com/convert/?query=https://arxiv.org/abs/1906.05664

![image](https://user-images.githubusercontent.com/306655/59701201-e771b480-91a9-11e9-8df1-844ffe36368c.png)

**Comment by bfirsh** [comment]
Ah - thank you! Fixed. Rendering server ran out of disk space. Seems like I should work on #86. ;)

**Comment by Wilfred** [comment]
@bfirsh looks like it's happening again: https://www.arxiv-vanity.com/papers/1808.04352/

Is it the same disk space issue?

**Comment by bfirsh** [comment]
Yeah - thank you. Currently fixing that and the root cause. A cron job to sweep up old renders was broken.

**Comment by bfirsh** [comment]
Hmm thanks. Not sure why that cron job is broken again.

**Comment by bfirsh** [comment]
I'll set up pingdom to force render a paper so we actually hear about this...

**Comment by Inazuma110** [comment]
The same problem seems to be happening.
https://www.arxiv-vanity.com/papers/2002.09460/

**Comment by bfirsh** [comment]
fixed -- thanks!

**Comment by bfirsh** [comment]
This is the proper fix https://github.com/arxiv-vanity/engrafo/issues/1022

**Comment by mplavala** [comment]
It seems that it happened again: https://www.arxiv-vanity.com/papers/2209.09942/
