### ISSUE TITLE
Bad rendering links to http://paper.pdf/

### ISSUE THREAD

**Issue by 007** [arxiv-vanity/arxiv-vanity#433]
https://www.arxiv-vanity.com/papers/1804.04076/ fetched the paper and "rendered" it, but the generated page is a list of links treating `.pdf` like `.com` and not showing any paper content.

I didn't get a chance to debug on non-mobile, but is this because the paper source doesn't specify a content type or file extension correctly?

**Comment by bfirsh** [comment]
Unfortunately this paper isn't in latex -- it's just embedding PDFs. :(

Thanks for the report!

**Comment by bfirsh** [comment]
It should show an error though - https://github.com/arxiv-vanity/engrafo/issues/343
