### ISSUE TITLE
https://arxiv.org/abs/1910.14161 has been "rendering" for a day now

### ISSUE THREAD

**Issue by igalic** [arxiv-vanity/arxiv-vanity#471]
I've been trying to access https://arxiv.org/abs/1910.14161 via https://www.arxiv-vanity.com/papers/1910.14161/ and it's been showing the same 

> [spinner]
>
> This paper is rendering! Your browser will automatically refresh when it is finished. It should take less than a minute.

for about a day now — on every device i try to access it from.

**Comment by stared** [comment]
I experience the same problem, e.g. with https://www.arxiv-vanity.com/papers/1907.05417/.

**Comment by vict0rsch** [comment]
This should be closed

**Comment by igalic** [comment]
closed.

although it would be nice to have a clearer message when something is taking more than a few minutes.

**Comment by bfirsh** [comment]
:+1: This is just because rendering system is held together with duct tape. I haven't got time to fix right now but PRs with more duct tape or some real engineering very welcome. XD
