### ISSUE TITLE
Images on paper list

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/arxiv-vanity#6]
Pick a suitable image from the article, somehow.

**Comment by 0bserver07** [comment]
Maybe check out `convert` command from [imagemagick](https://www.imagemagick.org/script/convert.php)

It allows doing things like this:   [source](https://stackoverflow.com/a/6605085/539075)

```shell
convert           \
   -verbose       \
   -density 150   \
   -trim          \
    test.pdf      \
   -quality 100   \
   -flatten       \
   -sharpen 0x1.0 \
    24-18.jpg
``` 


after installing the command-line tool, that command can be called from within python also, maybe in some shape or form like this:

```python 
Popen(['convert', '%s[0-1]' % (where_pdf_path_is, ), '-thumbnail', 'x156', os.path.join("/tmp/", 'thumb.png')])
```
