### ISSUE TITLE
Stop licences violation

### ISSUE THREAD

**Issue by thomasmach** [arxiv-vanity/arxiv-vanity#601]
Please add a check to restrict downloading papers to those published under a CC license, since the arXiv license does not allow you to alter and republish the work of other people.

**Comment by bfirsh** [comment]
Hi Thomas!

We're aware of this and working with arXiv to integrate into arXiv itself so there isn't this issue. So many people love arXiv Vanity (hundreds of thousands of people use it) that we nor arXiv want to stop it from working, despite it being on the wrong URL, if that makes sense. Consider arXiv Vanity a stop-gap until we can do it properly. :)

If there's a particular paper you'd like to take down, we'd be happy to do that.

**Comment by thomasmach** [comment]
I would like to point out to you that the in some jurisdictions copyright infringement is a criminal offense.
