### ISSUE TITLE
arXiv URLs with old-style identifiers do not work

### ISSUE THREAD

**Issue by a3nm** [arxiv-vanity/arxiv-vanity#69]
For instance, inputting "https://arxiv.org/abs/cs/0003044" on the landing page results in an error message "Could not find Arxiv ID in that URL. Are you sure it's an arxiv.org URL?"

**Comment by bfirsh** [comment]
Thanks for the report!

**Comment by bfirsh** [comment]
Another complication: bulk source files are named like `astro-ph9912010.gz` which needs converting from the format with a slash.

**Comment by bfirsh** [comment]
Oh nice, thank you!

Curious about what the crash is - would you mind posting error messages etc in another issue?

**Comment by drscotthawley** [comment]
@bfirsh I'm open to doing so if you like, but I'm not sure if it's a bug with your system or just that I've never used docker before.
The output log is so long (about 900 lines) I don't even know where the 'crucial' error(s) would be.  Not sure what to call the Issue other than "Doesn't work -- User error?"  Is that ok?  
...Honestly I was just noticing that this issue has sat unattended for so long, and I thought I could try to fix it so I could see what my old gr-qc papers look like. ;-)

**Comment by bfirsh** [comment]
Yes, that is fine!

Thanks for having a go anyway - this is one step done. :)

**Comment by bfirsh** [comment]
For you or anyone else curious about implementing this, I mentioned two things in #279 which need doing off the top of my head.

**Comment by epitron** [comment]
Just ran into this issue for https://arxiv.org/abs/hep-th/9711200

How's this coming? Is the fix complicated?

**Comment by notmgsk** [comment]
Still seeing this.
