### ISSUE TITLE
amsthm environnements (theorem, definition, etc.) are missing

### ISSUE THREAD

**Issue by a3nm** [arxiv-vanity/arxiv-vanity#71]
Just pointing out what seems to be a fairly annoying problem (at least for theoretical articles): all environments such as theorem, proof, definition, lemma, etc., from amsthm, seem to be removed. Here is an example of an article of mine where the problem occurs: https://www.arxiv-vanity.com/papers/1702.05589/ and here is another article https://www.arxiv-vanity.com/papers/1710.07572/. Note that the references to these environments are broken (e.g., "Theorem ?").

I hope this report is useful! Thanks for the service, I think it's a really great idea.

**Comment by a3nm** [comment]
Ah, this appears to be a duplicate of https://github.com/arxiv-vanity/engrafo/issues/157 -- sorry about that. Closing.

**Comment by bfirsh** [comment]
Thanks! Added those as examples to that issue :)
