### ISSUE TITLE
Missing close brace, Extra close brace or missing open brace

### ISSUE THREAD

**Issue by rmuratov** [arxiv-vanity/arxiv-vanity#74]
Sorry, I'm not into your tech stack, but just encountered a bug, I guess.

Check out [this paper](https://arxiv.org/abs/1710.07636). Arxiv-vanity appearance vs the same part in the original pdf. Tested in both Firefox 57 and latest Chrome.

![screenshot from 2017-10-24 09-57-17](https://user-images.githubusercontent.com/4287685/31928814-33d4d2f4-b8a2-11e7-902a-6b04f70bae90.png)
![screenshot from 2017-10-24 09-58-54](https://user-images.githubusercontent.com/4287685/31928815-33f6bdd8-b8a2-11e7-8ea1-c9bd9e34f78d.png)

**Comment by bfirsh** [comment]
Thanks for the detailed report! I’ve filed it here: https://github.com/arxiv-vanity/engrafo/issues/173
