### ISSUE TITLE
Add twitter and facebook link previews for papers

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/arxiv-vanity#77]

**Comment by wassname** [comment]
Perhaps reddit too, [example](https://chrome.google.com/webstore/detail/glfepofdcehcfjcibmdaajdhioiigkmh?utm_source=chrome-app-launcher-info-dialog).

**Comment by bfirsh** [comment]
fixed https://github.com/arxiv-vanity/arxiv-vanity/commit/932e89b1bc721ac53dcfe29f6e6b43655afa5b09
