### ISSUE TITLE
(Some?) URLs are being rendered as relative

### ISSUE THREAD

**Issue by mhart** [arxiv-vanity/arxiv-vanity#81]
Eg on https://www.arxiv-vanity.com/papers/1710.06542/

<img width="884" alt="screen shot 2017-10-24 at 9 18 24 am" src="https://user-images.githubusercontent.com/367936/31945165-5b4f7402-b89c-11e7-945b-8d24fe638867.png">

This URL resolves correctly to http://www.goo.gl/b57WTs in the original PDF

**Comment by bfirsh** [comment]
Ah, we’re probably not matching .gl. I’ve filed here: https://github.com/arxiv-vanity/engrafo/issues/174

Thanks for the report!
