### ISSUE TITLE
Maybe use pdf.js to capture graphical figures?

### ISSUE THREAD

**Issue by dosyago-coder-0** [arxiv-vanity/arxiv-vanity#87]
There are some beautiful figures in some pdfs on arxiv, such as in:

https://arxiv.org/pdf/1710.08919.pdf

and while the output of your tool as a web page for the paper's text is beautiful, 
and for its tables mostly so, there are none of the beautiful and colorful graphical 
figures that the pdf itself contains. 

Oh well! 

And otherwise, great work!!!!

**Comment by bfirsh** [comment]
We actually do this already by converting things like tikzpicture into SVGs. I think those figures aren't turning due to some other bug - I shall have to investigate.

I have created an issue here to investigate: https://github.com/arxiv-vanity/engrafo/issues/175

Thanks for the report!
