### ISSUE TITLE
Add URLs for references which point to arXiv

### ISSUE THREAD

**Issue by ApoorvaJ** [arxiv-vanity/arxiv-vanity#90]
The reference popup is really nice. It would be even nicer if the arXiv:[number] text was a URL that would take you to the corresponding arxiv-vanity.com/papers/[number] url.

![screenshot 2017-10-31 12 10 13](https://user-images.githubusercontent.com/2312221/32210705-2ecc5ffa-be35-11e7-8a49-03a0456513cc.png)

**Comment by bfirsh** [comment]
Now done! https://github.com/arxiv-vanity/engrafo/pull/526

I'll make its way to arxiv-vanity.com when I update the engrafo version.
