### ISSUE TITLE
Kill renders that have been running too long

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/arxiv-vanity#93]
Sometimes Engrafo hangs for some reason.

**Comment by bfirsh** [comment]
FWIW this hasn't really been an issue since we switched to LaTeXML. I think only one or two renders have hung. The most most recent was a stuck right at the end, after sending the webhook.

**Comment by anxingle** [comment]
running too long on my Mac and "http://localhost:8000/papers/1703.07815/" didn't show the whole paper(just show the title ). So, I wonder should we sign up Hyper.sh and  fill the ID  in some configure file?
